const initialState = [
    {
        id: 1,
        img: 'https://1b4da894acfad722fb46-08ede53a5c8850764384bc99fd6145bb.ssl.cf3.rackcdn.com/401182/32069122_u.jpg',
        name: 'Premier Inn Dubai International Airport',
        address: '52B Street, Opposite Terminal 3, ОАЭ, Дубай, 5.7 км до центра',
        averageCost: '8138 ₽',
        stars: '⭐⭐⭐',
        isFavorite: false,
        description: '«Premier Inn Dubai International Airport» 3* расположен в городе Дубай по адресу 52B Street, Opposite Terminal 3. По мнению постояльцев, отель имеет рейтинг 8.2 из 10. Здание отеля «Premier Inn Dubai International Airport» было построено в 2009. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 2,
        img: 'https://c.ekstatic.net/dex-media/503/Holiday-Inn-Express-Dubai-Airport-Desktop-HotelDetails-1-1.jpg',
        name: 'Holiday Inn Express Dubai Airport',
        address: '52B Street, Opposite Terminal 3, ОАЭ, Дубай, 5.7 км до центра',
        averageCost: '13049 ₽',
        stars: '⭐⭐⭐',
        isFavorite: false,
        description: '«Holiday Inn Express Dubai Airport» 3* расположен в городе Дубай по адресу Airport Road. По мнению постояльцев, отель имеет рейтинг 7.8 из 10. Здание отеля «Holiday Inn Express Dubai Airport» было построено в 2010. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 3,
        img: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/490808300.jpg?k=0127a1994d74af10eaa6460dd6846817e1a5ed082ec866562819adc9abdfa55c&o=&hp=1',
        name: 'Hilton Dubai Jumeirah',
        address: 'Jumeirah Beach Road, ОАЭ, Дубай, 26.33 км до центра',
        averageCost: "34036 ₽",
        stars: '⭐⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Hilton Dubai Jumeirah» 5* расположен в городе Дубай по адресу Jumeirah Beach Road. По мнению постояльцев, отель имеет рейтинг 7.9 из 10. Здание отеля «Hilton Dubai Jumeirah» было построено в 1999. У отеля есть выход к пляжу (первая линия). Вы можете посетить частный пляж при отеле. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. Для семейных гостей на территории отеля есть игровая площадка для детей. Если у вас есть важные дела и не с кем оставить детей, отель предоставит услуги няни. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 4,
        img: 'https://stopovertrips.com/images/Packages/atana/atana-3.jpg',
        name: 'Atana Hotel',
        address: 'Tecom, Hessa Street, Al Barsha South, ОАЭ, Дубай, 21.55 км до центра',
        averageCost: '13452 ₽',
        stars: '⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Atana Hotel» 4* расположен в городе Дубай по адресу Tecom, Hessa Street, Al Barsha South. По мнению постояльцев, отель имеет рейтинг 7.8 из 10. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. Для семейных гостей на территории отеля есть клуб для детей. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 5,
        img: 'https://bynder.onthebeach.co.uk/m/40ac29242c936a99/original/Fairmont-The-Palm.jpg',
        name: 'Fairmont The Palm',
        address: 'Palm Jumeirah , ОАЭ, Дубай, 23.28 км до центра',
        averageCost: '33427 ₽',
        stars: '⭐⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Fairmont The Palm» 5* расположен в городе Дубай по адресу Palm Jumeirah . По мнению постояльцев, отель имеет рейтинг 8 из 10. Здание отеля «Fairmont The Palm» было построено в 2012. У отеля есть выход к пляжу (первая линия). Вы можете посетить частный пляж при отеле. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. Для семейных гостей на территории отеля есть игровая площадка для детей. Если у вас есть важные дела и не с кем оставить детей, отель предоставит услуги няни. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 6,
        img: 'https://images.luxuryescapes.com/fl_progressive,q_auto:eco,c_scale,w_650/rcbat3pm5inzse56cga.jpeg',
        name: 'Relais & Châteaux Hotel Orfila',
        address: 'Orfila, 6, Испания, Мадрид, 1.45 км до центра',
        averageCost: '76903 ₽',
        stars: '⭐⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Relais & Châteaux Hotel Orfila» 5* расположен в городе Мадрид по адресу Orfila, 6. По мнению постояльцев, отель имеет рейтинг 9.2 из 10. Здание отеля «Relais & Châteaux Hotel Orfila» было построено в 1886. Последний раз его ремонтировали в 1999. Если у вас есть важные дела и не с кем оставить детей, отель предоставит услуги няни. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 7,
        img: 'https://media-cdn.tripadvisor.com/media/photo-s/26/74/35/6e/exterior.jpg',
        name: 'Hilton Madrid Airport',
        address: 'Avenida de la Hispanidad, 2-4, Испания, Мадрид, 10.66 км до центра',
        averageCost: '19865 ₽',
        stars: '⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Hilton Madrid Airport» 4* расположен в городе Мадрид по адресу Avenida de la Hispanidad, 2-4. По мнению постояльцев, отель имеет рейтинг 8.3 из 10. Здание отеля «Hilton Madrid Airport» было построено в 2008. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 8,
        img: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/28176197.jpg?k=9bbd83876050fbdc85c6a6fa4ef1d74ecfa1cdf6e44ef32f28af1e3ae0bc1b3f&o=&hp=1',
        name: 'Hotel Life Gran Via',
        address: 'Address 1',
        averageCost: '16896 ₽',
        stars: '⭐⭐',
        isFavorite: false,
        description: '«Hotel Life Gran Via» 2* расположен в городе Мадрид по адресу Pizarro, 16. По мнению постояльцев, отель имеет рейтинг 7.1 из 10. Здание отеля «Hotel Life Gran Via» было построено в 2008. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями.',
        reviews: [],
    },
    {
        id: 9,
        img: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/f0/cc/3c/habitacion-doble-premium.jpg?w=700&h=-1&s=1',
        name: 'B&B Hotel Madrid Centro Puerta del Sol',
        address: 'Calle de la Montera 10-12, Испания, Мадрид, 0.14 км до центра',
        averageCost: '31328 ₽',
        stars: '⭐⭐⭐',
        isFavorite: false,
        description: '«B&B Hotel Madrid Centro Puerta del Sol» 3* расположен в городе Мадрид по адресу Calle de la Montera 10-12. По мнению постояльцев, отель имеет рейтинг 9 из 10. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями.',
        reviews: [],
    },
    {
        id: 10,
        img: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/426619374.jpg?k=3a879e4d7a0ea6652cbde3a152108fc3438a03c01c1dd463bc1b8787c12f319a&o=&hp=1',
        name: 'Hotel Palacio del Retiro, Autograph Collection',
        address: 'Avenida Alfonso XII, 14, Испания, Мадрид, 1.15 км до центра',
        averageCost: '59819 ₽',
        stars: '⭐⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Hotel Palacio del Retiro, Autograph Collection» 5* расположен в городе Мадрид по адресу Avenida Alfonso XII, 14. По мнению постояльцев, отель имеет рейтинг 8.3 из 10. Здание отеля «Hotel Palacio del Retiro, Autograph Collection» было построено в 1904. Последний раз его ремонтировали в 2004. Если у вас есть важные дела и не с кем оставить детей, отель предоставит услуги няни. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 11,
        img: 'https://media-cdn.tripadvisor.com/media/photo-m/1280/27/6e/47/cc/caption.jpg',
        name: 'Residhome Paris Rosa Parks',
        address: '3 Rue Gaston Tessier, Франция, Париж, 4.97 км до центра',
        averageCost: '19212 ₽',
        stars: '⭐⭐⭐',
        isFavorite: false,
        description: '«Residhome Paris Rosa Parks» 3* расположен в городе Париж по адресу 3 Rue Gaston Tessier. По мнению постояльцев, отель имеет рейтинг 8.3 из 10. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 12,
        img: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/112995904.jpg?k=8040ae5ed4c9b01b2f395f96e640c10fadcbe305209e8e93bffdb566a98c5f65&o=&hp=1',
        name: 'Villa Montparnasse',
        address: '2, Rue Boulard, Франция, Париж, 2.49 км до центра',
        averageCost: '22647 ₽',
        stars: '⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Villa Montparnasse» 4* расположен в городе Париж по адресу 2, Rue Boulard. По мнению постояльцев, отель имеет рейтинг 7.7 из 10. Здание отеля «Villa Montparnasse» было построено в 1900. Последний раз его ремонтировали в 2001.',
        reviews: [],
    },
    {
        id: 13,
        img: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/123616147.jpg?k=30dfee670eef44b0ee1ebcd28894bc4110a0e152b25909fadacf358f39efeb96&o=&hp=1',
        name: 'Le Burgundy Paris',
        address: '6-8 Rue Duphot, Франция, Париж, 2.34 км до центра',
        averageCost: '94088 ₽',
        stars: '⭐⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Le Burgundy Paris» 5* расположен в городе Париж по адресу 6-8 Rue Duphot. По мнению постояльцев, отель имеет рейтинг 8.9 из 10. Здание отеля «Le Burgundy Paris» было построено в 1770. Последний раз его ремонтировали в 2010. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. Если у вас есть важные дела и не с кем оставить детей, отель предоставит услуги няни. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 14,
        img: 'https://dq5r178u4t83b.cloudfront.net/wp-content/uploads/sites/19/2018/12/18151313/4780-02-1.jpg',
        name: 'Sofitel Paris Le Faubourg',
        address: '15 Rue Boissy d Anglas, Франция, Париж, 2.58 км до центра',
        averageCost: '109001 ₽',
        stars: '⭐⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Sofitel Paris Le Faubourg» 5* расположен в городе Париж по адресу 15 Rue Boissy d Anglas. По мнению постояльцев, отель имеет рейтинг 8.1 из 10. Здание отеля «Sofitel Paris Le Faubourg» было построено в 1850. Последний раз его ремонтировали в 2012. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 15,
        img: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/170099365.jpg?k=0b9c24af4666e2b6784878567b7937ffdb4352e0404c03f89a07aab868fadef5&o=&hp=1',
        name: 'Paris Hotel',
        address: '3 Rue Henri Poincaré, Франция, Париж, 6.01 км до центра',
        averageCost: '10863 ₽',
        stars: '⭐⭐',
        isFavorite: false,
        description: '«Paris Hotel» 2* расположен в городе Париж по адресу 3 Rue Henri Poincaré. По мнению постояльцев, отель имеет рейтинг 7.5 из 10. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями.',
        reviews: [],
    },
    {
        id: 16,
        img: 'https://www.ahstatic.com/photos/5347_ho_00_p_1024x768.jpg',
        name: 'Pullman Berlin Schweizerhof',
        address: 'Budapester Str. 25, Германия, Берлин, 4.92 км до центра',
        averageCost: '67289 ₽',
        stars: '⭐⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Pullman Berlin Schweizerhof» 5* расположен в городе Берлин по адресу Budapester Str. 25. По мнению постояльцев, отель имеет рейтинг 8.5 из 10. Здание отеля «Pullman Berlin Schweizerhof» было построено в 1999. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 17,
        img: 'https://ak-d.tripcdn.com/images/220g0q000000g192q03CA_R_960_660_R5_D.jpg',
        name: 'Select Hotel Berlin Checkpoint Charlie',
        address: 'Hedemannstr. 11-12, Германия, Берлин, 2.75 км до центра',
        averageCost: '24027 ₽',
        stars: '⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Select Hotel Berlin Checkpoint Charlie» 4* расположен в городе Берлин по адресу Hedemannstr. 11-12. По мнению постояльцев, отель имеет рейтинг 7.8 из 10. Здание отеля «Select Hotel Berlin Checkpoint Charlie» было построено в 1926. Последний раз его ремонтировали в 2006. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 18,
        img: 'https://ak-d.tripcdn.com/images/0224z12000a38ro7q9536_R_960_660_R5_D.jpg',
        name: "Victor's Residenz-Hotel Berlin Tegel",
        address: 'Holländerstr. 31, Германия, Берлин, 5.65 км до центра',
        averageCost: '16238 ₽',
        stars: '⭐⭐⭐',
        isFavorite: false,
        description: "«Victor's Residenz-Hotel Berlin Tegel» 3* расположен в городе Берлин по адресу Holländerstr. 31. По мнению постояльцев, отель имеет рейтинг 7.6 из 10. Здание отеля «Victor's Residenz-Hotel Berlin Tegel» было построено в 1996. Последний раз его ремонтировали в 2004. Если у вас есть важные дела и не с кем оставить детей, отель предоставит услуги няни. На территории отеля есть конференц-зал.",
        reviews: [],
    },
    {
        id: 19,
        img: 'https://media-cdn.holidaycheck.com/w_768,h_432,c_fill,q_auto,f_auto/ugc/images/afc5a0a6-fe78-3a02-be60-3a5213760ff5',
        name: 'Dorint Kurfürstendamm Berlin',
        address: 'Augsburger Str. 41, Германия, Берлин, 5.84 км до центра',
        averageCost: '30979 ₽',
        stars: '⭐⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Dorint Kurfürstendamm Berlin» 5* расположен в городе Берлин по адресу Augsburger Str. 41. По мнению постояльцев, отель имеет рейтинг 8.3 из 10. Здание отеля «Dorint Kurfürstendamm Berlin» было построено в 2005. Мы рады всем, поэтому у нас есть сервисы для гостей с ограниченными физическими возможностями. Если у вас есть важные дела и не с кем оставить детей, отель предоставит услуги няни. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },
    {
        id: 20,
        img: 'https://park-plaza-wallstreet-berlin-mitte-hotel.nochi.com/data/Photos/OriginalPhoto/3099/309950/309950809/Park-Plaza-Wallstreet-Berlin-Mitte-Hotel-Exterior.JPEG',
        name: 'Park Plaza Wallstreet Berlin Mitte',
        address: 'Wallstr. 23-24, Германия, Берлин, 1.44 км до центра',
        averageCost: '37059 ₽',
        stars: '⭐⭐⭐⭐',
        isFavorite: false,
        description: '«Park Plaza Wallstreet Berlin Mitte» 4* расположен в городе Берлин по адресу Wallstr. 23-24. По мнению постояльцев, отель имеет рейтинг 8.2 из 10. Здание отеля «Park Plaza Wallstreet Berlin Mitte» было построено в 2006. Для важных гостей отель предоставляет v.i.p. услуги. На территории отеля есть конференц-зал.',
        reviews: [],
    },

];

const hotelsReducer = (state = initialState, action) => {
    switch (action.type) {
        case 'SET_FAVORITE':
            return state.map((hotel) =>
                hotel.id === action.payload.id
                    ? { ...hotel, isFavorite: action.payload.isFavorite }
                    : hotel
            );
        case 'REMOVE_FAVORITE':
            return {
                ...state,
                hotels: state.hotels.map((hotel) =>
                    hotel.id === action.payload
                        ? { ...hotel, isFavorite: false }
                        : hotel
                ),
            };
        default:
            return state;
    }
};

export default hotelsReducer;